<template>
  <div>
    <router-link :to="{name: 'contacto'}">
      <!-- <button
        class="sheen bg-gray-500 hover:bg-gray-600 text-white font-bold py-3 px-6 border-b-4 border-gray-700 hover:border-gray-500 rounded text-xl w-full"
      >Conocé nuestras oficinas</button> -->
      <button
        class="bg-gray-600 hover:bg-gray-700 text-white font-bold py-3 px-6 rounded text-xl w-full lg:w-2/5"
      >Conoce nuestras oficinas</button>
    </router-link>

    <transition name="fade">
      <div
        v-if="show"
        class="fixed bg-smoke bg-black lg:absolute top-0 left-0 h-screen w-full flex items-center justify-center z-50"
      >
        <div class="bg-white p-4 rounded w-full lg:w-2/6 text-gray-500">
          <div class="lg:flex">
            <h1 class="text-3xl w-full text-red-500">¡Contactese con nosotros!</h1>
          </div>

          <contact-form @close-button="show = !show" closeButton="true"></contact-form>
        </div>
      </div>
    </transition>
  </div>
</template>

<script>
import Modal from "vue-tailwind-modal";
import ContactForm from "../components/ContactForm";

export default {
  name: "PresupuestoButton",
  components: { Modal, ContactForm },
  data() {
    return {
      show: false
    };
  },
  methods: {
    goToContact() {
      window.location.href = "/contacto";
    }
  }
};
</script>

<style scoped>
.bg-smoke {
  background-color: rgba(0, 0, 0, 0.5);
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.3s;
}

.fade-enter,
.fade-leave-to {
  opacity: 0;
}

.heartbeat {
  animation: heartbeat 1.5s ease-in-out infinite both;
}
/* ----------------------------------------------
 * Generated by Animista on 2020-3-2 18:36:2
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

@keyframes heartbeat {
  from {
    transform: scale(1);
    transform-origin: center center;
    animation-timing-function: ease-out;
  }
  10% {
    transform: scale(0.91);
    animation-timing-function: ease-in;
  }
  17% {
    transform: scale(0.98);
    animation-timing-function: ease-out;
  }
  33% {
    transform: scale(0.87);
    animation-timing-function: ease-in;
  }
  45% {
    transform: scale(1);
    animation-timing-function: ease-out;
  }
}

.sheen {
  position: relative;
  overflow: hidden;
}

.sheen:after {
  animation: sheen 1s 0.1s forwards infinite;
  content: "";
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: linear-gradient(
    to bottom,
    transparent,
    rgba(255, 255, 255, 0.5) 50%,
    transparent
  );
  transform: rotateZ(60deg) translate(-1em, 4em);
}

@keyframes sheen {
  100% {
    transform: rotateZ(60deg) translate(0, -4em);
  }
}
</style>